### PR TITLE
 Adding a multiple dropdown for the target and agent in addition to the configuration of jobs for each task.

### PR DESCRIPTION
**Pull request by amma35**
Adding a multiple dropdown for the target and agent in addition to the configuration of jobs for each task.
see #13

### CODE REVIEW

**Comment by orthagh** [comment]
i have a problem with this commit.
first, i think it was a good enhancement but with a lot of items (thousand), the interface become laggy and unusable.
Each type on keyboard to filter list takes around 3 second to computer.
User experience is very bad.

It's a very urgent issue, so we need to review this list to support ajax (filtering and list limit) or i would have to revert commit

**Comment by orthagh** [comment]
My current test was with 11k computers in this list

**Comment by amma35** [comment]
With Dropdown::showFromArray(), we cannot the limit of the list but we can use multiple parameter.

With Dropdown::show() we can limit list (with $CFG_GLPI['dropdown_max']) but we cannot use multiple parameter. 

You think that we can modify the dropdown::show() function ), to add the multiple parameter for permit to limit the number of results ?

Or we can duplicate the show function into the plugin...

**Comment by orthagh** [comment]
I think both :
* PR to add multiple in glpi core Dropdown::show(...)
* and duplication (temporary) in fusion plugin

**Comment by orthagh** [comment]
as said, it's reverted for now.
I'll appreciate a new pr for this feature

**Comment by amma35** [comment]
By searching to solve the problem of slowness, I noticed that in the list of recipients in the notifications into the GLPI, there is also the slowness problems.

I noticed that this problem was due to the release of select2 (3.5.2).
The problem has been fixed in version 4.
https://github.com/select2/select2/issues/781

**Comment by orthagh** [comment]
yes but it seems a big work for now to update this lib in glpi.
It certainly require a major review on all glpi dropdowns.

As 9.1 is expected to be released soon (i'd like in july), i think we should repel the upgrade after.

Anyway, as said previously, i can accept a enhancement on glpi to permit support of multiples in Dropdown show to fix this issue.

Thank you for search.

**Pull request merged**
